clean up ci (#177)
* clean up ci

* -e

* move version to build

* trying

* set app version to public

* test prod env

* test

* test updating version

* test tag

* add deployment hook

* uncomment

* finalize

diff --git a/.github/workflows/deploy-prod.yaml b/.github/workflows/deploy-prod.yaml
--- a/.github/workflows/deploy-prod.yaml
+++ b/.github/workflows/deploy-prod.yaml
@@ -3,64 +3,23 @@ name: Deploy to Production
 env:
     VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
     VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
-    pscale_base_directory: .pscale/cli-helper-scripts
 
 on:
     workflow_dispatch:
 
 jobs:
-    Deploy-to-Production:
+    deploy:
+        name: Deploy to Production
         runs-on: ubuntu-latest
-        defaults:
-            run:
-                working-directory: ./${{ github.event.repository.name }}
+
         steps:
-            - name: Fail if branch is not main
-              if: github.ref != 'refs/heads/main'
-              run: |
-                  echo "This workflow should not be triggered on a branch other than main"
-                  exit 1
+            - name: Checkout
+              uses: actions/checkout@v4
 
-            - name: Check if user is a repo admin
-              working-directory: ./
+            - name: Download dependencies
               run: |
-                  if [[ $(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/collaborators/${{ github.actor }}/permission" | jq -r '.permission') != "admin" ]]; then
-                    echo "Only repo admins can run this action."
-                    exit 1
-                  fi
-
-            - name: Set up SSH
-              working-directory: ./
-              run: |
-                  mkdir -p ~/.ssh
-                  echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
-                  chmod 600 ~/.ssh/id_ed25519
-                  eval "$(ssh-agent -s)"
-                  ssh-add ~/.ssh/id_ed25519
-
-            - name: Config
-              working-directory: ./
-              run: |
-                  git config --global credential.helper store
-                  git config --global user.email "github-actions@raidhub.io"
-                  git config --global user.name "GitHub Actions"
-
-            - name: Clone Repo
-              working-directory: ./
-              run: |
-                  git clone git@github.com:Raid-Hub/${{ github.event.repository.name }}.git
-
-            - name: Yarn install
-              run: yarn install
-
-            - name: Bump Version
-              run: |
-                  VERSION=$(./bump.sh)
-                  echo "Version: $VERSION"
-                  echo "VERSION=$VERSION" >> $GITHUB_ENV
-                  git add package.json
-                  git add public/manifest.json
-                  git commit -m "Bump $VERSION"
+                  yarn install
+                  yarn prisma generate
 
             - name: Install Turso CLI
               env:
@@ -69,25 +28,66 @@ jobs:
                   curl -sSfL https://get.tur.so/install.sh | bash
                   echo "PATH=$PATH:/home/runner/.turso" >> $GITHUB_ENV
 
+            - name: Pull Vercel Environment Information
+              run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
+
+            - name: Set APP_VERSION
+              shell: bash
+              run: |
+                  VERSION=$(grep -E '^APP_VERSION=' .vercel/.env.production.local | cut -d '=' -f 2)
+
+                  VERSION_ARRAY=(${VERSION//./ })
+
+                  # Get the first three numbers in the version
+                  YEAR=${VERSION_ARRAY[0]}
+                  MONTH=${VERSION_ARRAY[1]}
+                  DAY=${VERSION_ARRAY[2]}
+                  PATCH=${VERSION_ARRAY[3]}
+
+                  # Get the current year, month, and day
+                  CURRENT_YEAR=$(date +%Y)
+                  CURRENT_MONTH=$(date +%-m)
+                  CURRENT_DAY=$(date +%-d)
+
+                  # Check if the major, minor, and patch version numbers match the current date
+                  if [[ "$YEAR" == "$CURRENT_YEAR" && "$MONTH" == "$CURRENT_MONTH" && "$DAY" == "$CURRENT_DAY" ]]; then
+                    PATCH=$((PATCH+1))
+                  else
+                    PATCH=0
+                  fi
+
+                  echo "APP_VERSION=${CURRENT_YEAR}.${CURRENT_MONTH}.${CURRENT_DAY}.${PATCH}" >> $GITHUB_ENV
+
             - name: Apply Database Migrations
               env:
                   TURSO_DATABASE_NAME: ${{ secrets.TURSO_PROD_DATABASE_NAME }}
                   TURSO_API_TOKEN: ${{ secrets.TURSO_API_TOKEN }}
               run: ./.github/scripts/turso-migrate.sh
 
-            - name: Pull Vercel Environment Information
-              run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
-
-            - name: Build Project Artifacts
+            - name: Update Vercel Environment Information
               run: |
-                  yarn prisma generate
-                  vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
-
-            - name: Deploy Project Artifacts to Vercel
-              run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
+                  vercel env rm APP_VERSION production --yes --token=${{ secrets.VERCEL_TOKEN }}
+                  echo "$APP_VERSION" | vercel env add APP_VERSION production --token=${{ secrets.VERCEL_TOKEN }}
 
             - name: Create Tag
               run: |
-                  git tag -a v$${{ env.VERSION }} main -m "$(git log --pretty=format:"%s" main..HEAD)"
-                  git push origin
-                  git push --tags
+                  TAG_NAME="v$APP_VERSION"
+                  COMMIT_SHA="${{ github.sha }}"
+                  OWNER=$(echo "${{ github.repository }}" | cut -d '/' -f 1)
+                  REPO=$(echo "${{ github.repository }}" | cut -d '/' -f 2)
+
+                  curl -X POST \
+                    -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
+                    -H "Accept: application/vnd.github.v3+json" \
+                    "https://api.github.com/repos/$OWNER/$REPO/git/refs" \
+                    -d "{\"ref\":\"refs/tags/$TAG_NAME\",\"sha\":\"$COMMIT_SHA\",\"tagger\":{\"name\":\"${{ github.actor }}\",\"email\":\"${{ github.actor }}@users.noreply.github.com\",\"date\":\"$(date --iso-8601=seconds)\"}}"
+
+            - name: Deploy Project to Vercel
+              run: |
+                  res=$(curl -X POST ${{ secrets.VERCEL_PROD_DEPLOYMENT_HOOK }})
+                  if [[ $(echo "$res" | jq '.job.state == "PENDING"') == true ]]; then
+                    echo "Deployment is pending"
+                  else
+                    echo "Deployment failed"
+                    exit 1
+                  fi
