Fixed CI for real this time (#178)
* test deploy prod

* test

* f

* sleep

* t

* t

* take 72

* take 73

* for loop

* fixed it

diff --git a/.github/workflows/deploy-prod.yaml b/.github/workflows/deploy-prod.yaml
--- a/.github/workflows/deploy-prod.yaml
+++ b/.github/workflows/deploy-prod.yaml
@@ -64,12 +64,8 @@ jobs:
                   TURSO_API_TOKEN: ${{ secrets.TURSO_API_TOKEN }}
               run: ./.github/scripts/turso-migrate.sh
 
-            - name: Update Vercel Environment Information
-              run: |
-                  vercel env rm APP_VERSION production --yes --token=${{ secrets.VERCEL_TOKEN }}
-                  echo "$APP_VERSION" | vercel env add APP_VERSION production --token=${{ secrets.VERCEL_TOKEN }}
-
             - name: Deploy Project to Vercel
+              shell: bash
               run: |
                   # Deployments are triggered when DEPLOY_HOOK_TRIGGER environment variable is set
                   echo $APP_VERSION | vercel env add DEPLOY_HOOK_TRIGGER production --token=${{ secrets.VERCEL_TOKEN }}
@@ -78,8 +74,21 @@ jobs:
 
                   if [[ $(echo "$res" | jq '.job.state == "PENDING"') == true ]]; then
                     echo "Deployment is pending"
+                    sleep 5
+                    list=$(vercel list --environment production --token=${{ secrets.VERCEL_TOKEN }} 2>&1 1>/dev/null)
+                    url=$(echo $list | awk '{for(i=1;i<=NF;i++) if($i == "●" && $(i+1) == "Building") print $(i-1)}')
+                    echo "Deployment URL: $url"
+                    deployment=$(vercel inspect $url --wait --timeout 5m --scope raidhub --token=${{ secrets.VERCEL_TOKEN }} 2>&1)
+
+                    if echo $deployment | grep -q "● Ready"; then
+                      echo "Deployment successful"
+                      vercel inspect $url --scope raidhub --token=${{ secrets.VERCEL_TOKEN }}
+                    else
+                      echo "Deployment failed"
+                      exit 1
+                    fi
                   else
-                    echo "Deployment failed"
+                    echo "Deployment trigger failed"
                     exit 1
                   fi
 
@@ -95,3 +104,8 @@ jobs:
                     -H "Accept: application/vnd.github.v3+json" \
                     "https://api.github.com/repos/$OWNER/$REPO/git/refs" \
                     -d "{\"ref\":\"refs/tags/$TAG_NAME\",\"sha\":\"$COMMIT_SHA\",\"tagger\":{\"name\":\"${{ github.actor }}\",\"email\":\"${{ github.actor }}@users.noreply.github.com\",\"date\":\"$(date --iso-8601=seconds)\"}}"
+
+            - name: Update Vercel Environment Information
+              run: |
+                  vercel env rm APP_VERSION production --yes --token=${{ secrets.VERCEL_TOKEN }}
+                  echo "$APP_VERSION" | vercel env add APP_VERSION production --token=${{ secrets.VERCEL_TOKEN }}
