disable auto deploy

diff --git a/.github/workflows/deploy-prod.yaml b/.github/workflows/deploy-prod.yaml
--- a/.github/workflows/deploy-prod.yaml
+++ b/.github/workflows/deploy-prod.yaml
@@ -69,6 +69,20 @@ jobs:
                   vercel env rm APP_VERSION production --yes --token=${{ secrets.VERCEL_TOKEN }}
                   echo "$APP_VERSION" | vercel env add APP_VERSION production --token=${{ secrets.VERCEL_TOKEN }}
 
+            - name: Deploy Project to Vercel
+              run: |
+                  # Deployments are triggered when DEPLOY_HOOK_TRIGGER environment variable is set
+                  echo $APP_VERSION | vercel env add DEPLOY_HOOK_TRIGGER production --token=${{ secrets.VERCEL_TOKEN }}
+                  res=$(curl -X POST ${{ secrets.VERCEL_PROD_DEPLOYMENT_HOOK }})
+                  vercel env rm DEPLOY_HOOK_TRIGGER production --yes --token=${{ secrets.VERCEL_TOKEN }}
+
+                  if [[ $(echo "$res" | jq '.job.state == "PENDING"') == true ]]; then
+                    echo "Deployment is pending"
+                  else
+                    echo "Deployment failed"
+                    exit 1
+                  fi
+
             - name: Create Tag
               run: |
                   TAG_NAME="v$APP_VERSION"
@@ -81,13 +95,3 @@ jobs:
                     -H "Accept: application/vnd.github.v3+json" \
                     "https://api.github.com/repos/$OWNER/$REPO/git/refs" \
                     -d "{\"ref\":\"refs/tags/$TAG_NAME\",\"sha\":\"$COMMIT_SHA\",\"tagger\":{\"name\":\"${{ github.actor }}\",\"email\":\"${{ github.actor }}@users.noreply.github.com\",\"date\":\"$(date --iso-8601=seconds)\"}}"
-
-            - name: Deploy Project to Vercel
-              run: |
-                  res=$(curl -X POST ${{ secrets.VERCEL_PROD_DEPLOYMENT_HOOK }})
-                  if [[ $(echo "$res" | jq '.job.state == "PENDING"') == true ]]; then
-                    echo "Deployment is pending"
-                  else
-                    echo "Deployment failed"
-                    exit 1
-                  fi
